site:
  name: mediteranobay travel
  description: "Discover the beauty of Mediteranobay with our travel guide. Explore stunning beaches, vibrant culture, and unforgettable experiences."
  site: 'https://mediteranobay.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Mediteranobay travel
    template: '%s — AstroWind'
  description: "\U0001F680 Aktiva resor för grupper och företag. Upptäck den vilda Montenegro."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Mediteranobay travel
    images:
      - url: '~/assets/images/MB.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blogg' # (sv) ändrat från 'blog' – huvudväg blir /blogg
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
    id: 'G-7JZNBLDK5X' # Replace with your actual Measurement ID
   

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
